export type CanonBook = {
  id: string;
  order: number;
  testament: "AT" | "NT";
  name: string;
  abbreviation: string;
  chapters: number;
};

export const catholicCanon: CanonBook[] = [
  { id: "genesis", order: 1, testament: "AT", name: "Gênesis", abbreviation: "Gn", chapters: 50 },
  { id: "exodo", order: 2, testament: "AT", name: "Êxodo", abbreviation: "Ex", chapters: 40 },
  { id: "levitico", order: 3, testament: "AT", name: "Levítico", abbreviation: "Lv", chapters: 27 },
  { id: "numeros", order: 4, testament: "AT", name: "Números", abbreviation: "Nm", chapters: 36 },
  { id: "deuteronomio", order: 5, testament: "AT", name: "Deuteronômio", abbreviation: "Dt", chapters: 34 },
  { id: "josue", order: 6, testament: "AT", name: "Josué", abbreviation: "Js", chapters: 24 },
  { id: "juizes", order: 7, testament: "AT", name: "Juízes", abbreviation: "Jz", chapters: 21 },
  { id: "rute", order: 8, testament: "AT", name: "Rute", abbreviation: "Rt", chapters: 4 },
  { id: "1-samuel", order: 9, testament: "AT", name: "1 Samuel", abbreviation: "1Sm", chapters: 31 },
  { id: "2-samuel", order: 10, testament: "AT", name: "2 Samuel", abbreviation: "2Sm", chapters: 24 },
  { id: "1-reis", order: 11, testament: "AT", name: "1 Reis", abbreviation: "1Rs", chapters: 22 },
  { id: "2-reis", order: 12, testament: "AT", name: "2 Reis", abbreviation: "2Rs", chapters: 25 },
  { id: "1-cronicas", order: 13, testament: "AT", name: "1 Crônicas", abbreviation: "1Cr", chapters: 29 },
  { id: "2-cronicas", order: 14, testament: "AT", name: "2 Crônicas", abbreviation: "2Cr", chapters: 36 },
  { id: "esdras", order: 15, testament: "AT", name: "Esdras", abbreviation: "Esd", chapters: 10 },
  { id: "neemias", order: 16, testament: "AT", name: "Neemias", abbreviation: "Ne", chapters: 13 },
  { id: "tobias", order: 17, testament: "AT", name: "Tobias", abbreviation: "Tb", chapters: 14 },
  { id: "judite", order: 18, testament: "AT", name: "Judite", abbreviation: "Jt", chapters: 16 },
  { id: "ester", order: 19, testament: "AT", name: "Ester", abbreviation: "Est", chapters: 16 },
  { id: "1-macabeus", order: 20, testament: "AT", name: "1 Macabeus", abbreviation: "1Mc", chapters: 16 },
  { id: "2-macabeus", order: 21, testament: "AT", name: "2 Macabeus", abbreviation: "2Mc", chapters: 15 },
  { id: "job", order: 22, testament: "AT", name: "Jó", abbreviation: "Jó", chapters: 42 },
  { id: "salmos", order: 23, testament: "AT", name: "Salmos", abbreviation: "Sl", chapters: 150 },
  { id: "proverbios", order: 24, testament: "AT", name: "Provérbios", abbreviation: "Pr", chapters: 31 },
  { id: "eclesiastes", order: 25, testament: "AT", name: "Eclesiastes", abbreviation: "Ecl", chapters: 12 },
  { id: "cantares", order: 26, testament: "AT", name: "Cântico dos Cânticos", abbreviation: "Ct", chapters: 8 },
  { id: "sabedoria", order: 27, testament: "AT", name: "Sabedoria", abbreviation: "Sb", chapters: 19 },
  { id: "eclesiastico", order: 28, testament: "AT", name: "Eclesiástico", abbreviation: "Eclo", chapters: 51 },
  { id: "isaias", order: 29, testament: "AT", name: "Isaías", abbreviation: "Is", chapters: 66 },
  { id: "jeremias", order: 30, testament: "AT", name: "Jeremias", abbreviation: "Jr", chapters: 52 },
  { id: "lamentacoes", order: 31, testament: "AT", name: "Lamentações", abbreviation: "Lm", chapters: 5 },
  { id: "baruc", order: 32, testament: "AT", name: "Baruc", abbreviation: "Br", chapters: 6 },
  { id: "ezequiel", order: 33, testament: "AT", name: "Ezequiel", abbreviation: "Ez", chapters: 48 },
  { id: "daniel", order: 34, testament: "AT", name: "Daniel", abbreviation: "Dn", chapters: 14 },
  { id: "oseias", order: 35, testament: "AT", name: "Oseias", abbreviation: "Os", chapters: 14 },
  { id: "joel", order: 36, testament: "AT", name: "Joel", abbreviation: "Jl", chapters: 4 },
  { id: "amos", order: 37, testament: "AT", name: "Amós", abbreviation: "Am", chapters: 9 },
  { id: "obadias", order: 38, testament: "AT", name: "Obadias", abbreviation: "Ob", chapters: 1 },
  { id: "jonas", order: 39, testament: "AT", name: "Jonas", abbreviation: "Jn", chapters: 4 },
  { id: "miqueias", order: 40, testament: "AT", name: "Miqueias", abbreviation: "Mq", chapters: 7 },
  { id: "naum", order: 41, testament: "AT", name: "Naum", abbreviation: "Na", chapters: 3 },
  { id: "habacuc", order: 42, testament: "AT", name: "Habacuc", abbreviation: "Hab", chapters: 3 },
  { id: "sofonias", order: 43, testament: "AT", name: "Sofonias", abbreviation: "Sf", chapters: 3 },
  { id: "ageu", order: 44, testament: "AT", name: "Ageu", abbreviation: "Ag", chapters: 2 },
  { id: "zacarias", order: 45, testament: "AT", name: "Zacarias", abbreviation: "Zc", chapters: 14 },
  { id: "malaquias", order: 46, testament: "AT", name: "Malaquias", abbreviation: "Ml", chapters: 3 },
  { id: "mateus", order: 47, testament: "NT", name: "Mateus", abbreviation: "Mt", chapters: 28 },
  { id: "marcos", order: 48, testament: "NT", name: "Marcos", abbreviation: "Mc", chapters: 16 },
  { id: "lucas", order: 49, testament: "NT", name: "Lucas", abbreviation: "Lc", chapters: 24 },
  { id: "joao", order: 50, testament: "NT", name: "João", abbreviation: "Jo", chapters: 21 },
  { id: "atos", order: 51, testament: "NT", name: "Atos", abbreviation: "At", chapters: 28 },
  { id: "romanos", order: 52, testament: "NT", name: "Romanos", abbreviation: "Rm", chapters: 16 },
  { id: "1-corintios", order: 53, testament: "NT", name: "1 Coríntios", abbreviation: "1Cor", chapters: 16 },
  { id: "2-corintios", order: 54, testament: "NT", name: "2 Coríntios", abbreviation: "2Cor", chapters: 13 },
  { id: "galatas", order: 55, testament: "NT", name: "Gálatas", abbreviation: "Gl", chapters: 6 },
  { id: "efesios", order: 56, testament: "NT", name: "Efésios", abbreviation: "Ef", chapters: 6 },
  { id: "filipenses", order: 57, testament: "NT", name: "Filipenses", abbreviation: "Fl", chapters: 4 },
  { id: "colossenses", order: 58, testament: "NT", name: "Colossenses", abbreviation: "Cl", chapters: 4 },
  { id: "1-tessalonicenses", order: 59, testament: "NT", name: "1 Tessalonicenses", abbreviation: "1Ts", chapters: 5 },
  { id: "2-tessalonicenses", order: 60, testament: "NT", name: "2 Tessalonicenses", abbreviation: "2Ts", chapters: 3 },
  { id: "1-timoteo", order: 61, testament: "NT", name: "1 Timóteo", abbreviation: "1Tm", chapters: 6 },
  { id: "2-timoteo", order: 62, testament: "NT", name: "2 Timóteo", abbreviation: "2Tm", chapters: 4 },
  { id: "tito", order: 63, testament: "NT", name: "Tito", abbreviation: "Tt", chapters: 3 },
  { id: "filemon", order: 64, testament: "NT", name: "Filêmon", abbreviation: "Fm", chapters: 1 },
  { id: "hebreus", order: 65, testament: "NT", name: "Hebreus", abbreviation: "Hb", chapters: 13 },
  { id: "tiago", order: 66, testament: "NT", name: "Tiago", abbreviation: "Tg", chapters: 5 },
  { id: "1-pedro", order: 67, testament: "NT", name: "1 Pedro", abbreviation: "1Pd", chapters: 5 },
  { id: "2-pedro", order: 68, testament: "NT", name: "2 Pedro", abbreviation: "2Pd", chapters: 3 },
  { id: "1-joao", order: 69, testament: "NT", name: "1 João", abbreviation: "1Jo", chapters: 5 },
  { id: "2-joao", order: 70, testament: "NT", name: "2 João", abbreviation: "2Jo", chapters: 1 },
  { id: "3-joao", order: 71, testament: "NT", name: "3 João", abbreviation: "3Jo", chapters: 1 },
  { id: "judas", order: 72, testament: "NT", name: "Judas", abbreviation: "Jd", chapters: 1 },
  { id: "apocalipse", order: 73, testament: "NT", name: "Apocalipse", abbreviation: "Ap", chapters: 22 },
];

export const catholicCanonById = new Map(catholicCanon.map((book) => [book.id, book]));